In [1]:
import pandas as pd

#### diagnoses are icd 10 codes, 3 digit resolution
there's columns for date of appearance, for htose with it, per code in order. Seperated by "|"

In [2]:
df_diag = pd.read_csv("diagnosis.csv.gz")
df_diag

/var/folders/hl/bb0z87yd5pzfcp81jc8662kr0000gn/T/ipykernel_56024/983120802.py:1: DtypeWarning: Columns (98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,253,255) have mixed types. Specify dtype option on import or set low_memory=False.
  df_diag = pd.read_csv("diagnosis.csv.gz")

,Participant ID,Year of birth(participant - p34),Year of birth(participant - p22200),Had menopause | Instance 0,Had menopause | Instance 1,Had menopause | Instance 2,Had menopause | Instance 3,Sex,Diagnoses - ICD10,Date of first in-patient diagnosis - ICD10 | Array 0,...,Date of first in-patient diagnosis - ICD10 | Array 237,Date of first in-patient diagnosis - ICD10 | Array 238,Date of first in-patient diagnosis - ICD10 | Array 239,Date of first in-patient diagnosis - ICD10 | Array 240,Date of first in-patient diagnosis - ICD10 | Array 241,Date of first in-patient diagnosis - ICD10 | Array 242,Age at menopause (last menstrual period) | Instance 0,Age at menopause (last menstrual period) | Instance 1,Age at menopause (last menstrual period) | Instance 2,Age at menopause (last menstrual period) | Instance 3
0,1000015,1951.0,NaN,Yes,NaN,NaN,NaN,Female,K21.9 Gastro-oesophageal reflux disease withou...,2013-09-05,...,NaN,NaN,NaN,NaN,NaN,NaN,51,NaN,NaN,NaN
1,1000053,1944.0,NaN,Yes,NaN,NaN,NaN,Female,S22.30 Fracture of rib (closed)|S27.10 Traumat...,2006-09-14,...,NaN,NaN,NaN,NaN,NaN,NaN,50,NaN,NaN,NaN
2,1000132,1952.0,1952.0,NaN,NaN,NaN,NaN,Male,"D50.9 Iron deficiency anaemia, unspecified|D64...",2012-12-13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1000148,1944.0,NaN,Yes,NaN,NaN,NaN,Female,"F32.9 Depressive episode, unspecified|I10 Esse...",2019-02-11,...,NaN,NaN,NaN,NaN,NaN,NaN,47,NaN,NaN,NaN
4,1000163,1953.0,1953.0,NaN,NaN,NaN,NaN,Male,K92.1 Melaena,2014-08-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502405,6025912,1945.0,NaN,NaN,NaN,NaN,NaN,Male,A04.5 Campylobacter enteritis|C18.4 Transverse...,2004-10-08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
502406,6026091,1951.0,NaN,NaN,NaN,NaN,NaN,Male,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
502407,6026127,1946.0,NaN,NaN,NaN,NaN,NaN,Male,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
502408,6026153,1961.0,NaN,Not sure - other reason,NaN,NaN,NaN,Female,E78.0 Pure hypercholesterolaemia|H02.9 Disorde...,2021-01-08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
502409,6026188,1960.0,NaN,NaN,NaN,NaN,NaN,Male,C61 Malignant neoplasm of prostate|Z46.6 Fitti...,2017-04-04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
## cholesterol nmr df - filter by this
filt_df = df = pd.read_csv("Cholesterol_miki_participant.csv.gz").dropna(thresh=5,axis=0)
print(filt_df.shape)
filt_ids = list(filt_df["Participant ID"].unique())
print(len(filt_ids),"# filt IDs")

(121731, 69)
121731 # filt IDs

In [4]:
df_diag = df_diag.loc[df_diag['Participant ID'].isin(filt_ids)]
df_diag.shape[0]

121731

In [5]:
df_diag.columns

Index(['Participant ID', 'Year of birth(participant - p34)',
       'Year of birth(participant - p22200)', 'Had menopause | Instance 0',
       'Had menopause | Instance 1', 'Had menopause | Instance 2',
       'Had menopause | Instance 3', 'Sex', 'Diagnoses - ICD10',
       'Date of first in-patient diagnosis - ICD10 | Array 0',
       ...
       'Date of first in-patient diagnosis - ICD10 | Array 237',
       'Date of first in-patient diagnosis - ICD10 | Array 238',
       'Date of first in-patient diagnosis - ICD10 | Array 239',
       'Date of first in-patient diagnosis - ICD10 | Array 240',
       'Date of first in-patient diagnosis - ICD10 | Array 241',
       'Date of first in-patient diagnosis - ICD10 | Array 242',
       'Age at menopause (last menstrual period) | Instance 0',
       'Age at menopause (last menstrual period) | Instance 1',
       'Age at menopause (last menstrual period) | Instance 2',
       'Age at menopause (last menstrual period) | Instance 3'],
      dtype='object', length=256)

In [6]:
df_diag["Year of birth"] = df_diag['Year of birth(participant - p34)'].fillna(df_diag['Year of birth(participant - p22200)'])

df_diag['Diagnoses - ICD10'].fillna("",inplace=True)

/var/folders/hl/bb0z87yd5pzfcp81jc8662kr0000gn/T/ipykernel_56024/2570737166.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_diag["Year of birth"] = df_diag['Year of birth(participant - p34)'].fillna(df_diag['Year of birth(participant - p22200)'])
/var/folders/hl/bb0z87yd5pzfcp81jc8662kr0000gn/T/ipykernel_56024/2570737166.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_diag['Diagnoses - ICD10'].fillna("",inplace=True)

In [7]:
df_diag = df_diag[['Participant ID', "Year of birth",
                   'Sex', 'Diagnoses - ICD10']].drop_duplicates()

df_diag

,Participant ID,Year of birth,Sex,Diagnoses - ICD10
1,1000053,1944.0,Female,S22.30 Fracture of rib (closed)|S27.10 Traumat...
4,1000163,1953.0,Male,K92.1 Melaena
8,1000561,1962.0,Female,G56.0 Carpal tunnel syndrome|I10 Essential (pr...
21,1000981,1956.0,Female,"F41.9 Anxiety disorder, unspecified|G12.2 Moto..."
29,1001399,1957.0,Male,K40.9 Unilateral or unspecified inguinal herni...
...,...,...,...,...
502391,6025353,1954.0,Male,A09.9 Gastroenteritis and colitis of unspecifi...
502394,6025431,1962.0,Male,"M16.9 Coxarthrosis, unspecified|M25.85 Other s..."
502400,6025660,1962.0,Female,"J33.9 Nasal polyp, unspecified|K62.0 Anal poly..."
502403,6025855,1954.0,Female,"D26.1 Corpus uteri|H26.9 Cataract, unspecified..."
502409,6026188,1960.0,Male,C61 Malignant neoplasm of prostate|Z46.6 Fitti...

In [8]:
df_diag.nunique()

Participant ID       121731
Year of birth            37
Sex                       2
Diagnoses - ICD10     98259
dtype: int64

In [9]:
df_diag.isna().max()

Participant ID       False
Year of birth        False
Sex                  False
Diagnoses - ICD10    False
dtype: bool

In [10]:
df_diag[df_diag["Diagnoses - ICD10"].str.contains("E78.01",case=False,na=False)]# no res

Empty DataFrame
Columns: [Participant ID, Year of birth, Sex, Diagnoses - ICD10]
Index: []

In [11]:
df_diag[df_diag["Diagnoses - ICD10"].str.contains("E78.0",case=False,na=False)]

,Participant ID,Year of birth,Sex,Diagnoses - ICD10
30,1001528,1945.0,Male,E11.9 Without complications|E78.0 Pure hyperch...
55,1003005,1948.0,Male,D12.8 Rectum|E78.0 Pure hypercholesterolaemia|...
95,1004835,1949.0,Female,E78.0 Pure hypercholesterolaemia|K37 Unspecifi...
103,1005225,1957.0,Male,D17.1 Benign lipomatous neoplasm of skin and s...
124,1006173,1941.0,Male,D12.0 Caecum|D12.3 Transverse colon|D12.5 Sigm...
...,...,...,...,...
502319,6022394,1940.0,Male,A09.9 Gastroenteritis and colitis of unspecifi...
502349,6023714,1947.0,Male,B96.2 Escherichia coli [E. coli] as the cause ...
502364,6024151,1941.0,Male,C20 Malignant neoplasm of rectum|D51.9 Vitamin...
502375,6024596,1963.0,Male,"C44.7 Skin of lower limb, including hip|E78.0 ..."
502388,6025195,1941.0,Male,E11.9 Without complications|E78.0 Pure hyperch...

In [12]:
df_diag[df_diag["Diagnoses - ICD10"].str.contains("Familial hyper",case=False,na=False)]

Empty DataFrame
Columns: [Participant ID, Year of birth, Sex, Diagnoses - ICD10]
Index: []

In [13]:
df_diag.dropna()

,Participant ID,Year of birth,Sex,Diagnoses - ICD10
1,1000053,1944.0,Female,S22.30 Fracture of rib (closed)|S27.10 Traumat...
4,1000163,1953.0,Male,K92.1 Melaena
8,1000561,1962.0,Female,G56.0 Carpal tunnel syndrome|I10 Essential (pr...
21,1000981,1956.0,Female,"F41.9 Anxiety disorder, unspecified|G12.2 Moto..."
29,1001399,1957.0,Male,K40.9 Unilateral or unspecified inguinal herni...
...,...,...,...,...
502391,6025353,1954.0,Male,A09.9 Gastroenteritis and colitis of unspecifi...
502394,6025431,1962.0,Male,"M16.9 Coxarthrosis, unspecified|M25.85 Other s..."
502400,6025660,1962.0,Female,"J33.9 Nasal polyp, unspecified|K62.0 Anal poly..."
502403,6025855,1954.0,Female,"D26.1 Corpus uteri|H26.9 Cataract, unspecified..."
502409,6026188,1960.0,Male,C61 Malignant neoplasm of prostate|Z46.6 Fitti...

In [14]:
df_diag[df_diag["Diagnoses - ICD10"].str.contains("I25",case=False,na=False)]

,Participant ID,Year of birth,Sex,Diagnoses - ICD10
30,1001528,1945.0,Male,E11.9 Without complications|E78.0 Pure hyperch...
55,1003005,1948.0,Male,D12.8 Rectum|E78.0 Pure hypercholesterolaemia|...
103,1005225,1957.0,Male,D17.1 Benign lipomatous neoplasm of skin and s...
124,1006173,1941.0,Male,D12.0 Caecum|D12.3 Transverse colon|D12.5 Sigm...
192,1010183,1944.0,Male,"E66.9 Obesity, unspecified|H04.5 Stenosis and ..."
...,...,...,...,...
502349,6023714,1947.0,Male,B96.2 Escherichia coli [E. coli] as the cause ...
502364,6024151,1941.0,Male,C20 Malignant neoplasm of rectum|D51.9 Vitamin...
502375,6024596,1963.0,Male,"C44.7 Skin of lower limb, including hip|E78.0 ..."
502388,6025195,1941.0,Male,E11.9 Without complications|E78.0 Pure hyperch...
502391,6025353,1954.0,Male,A09.9 Gastroenteritis and colitis of unspecifi...

In [15]:
# df = df_diag.head(5000).copy()

df = df_diag.copy()

In [16]:
%%time
# Re-implementing the process without explicitly using an extra 'index' column

K_value = 100#2_500

# Start by creating a long format dataframe of diagnoses directly from the original dataframe, preserving the index
diagnoses_long_df_refined = df['Diagnoses - ICD10'].str.split('|', expand=True).stack().reset_index(level=1, drop=True).to_frame('Diagnosis')
# diagnoses_long_df_refined['ICD10_code'] = diagnoses_long_df_refined['Diagnosis'].apply(lambda x: x.split(' ')[0])
diagnoses_long_df_refined['ICD10_code'] = diagnoses_long_df_refined['Diagnosis']


# Count occurrences and filter codes as before
code_counts_refined = diagnoses_long_df_refined['ICD10_code'].value_counts()
print(len(code_counts_refined),"# all code_counts")
codes_to_keep_refined = code_counts_refined[code_counts_refined >= K_value].index
print(len(codes_to_keep_refined),"# codes_to_keep_refined")
# Filter diagnoses to keep only frequently occurring codes
filtered_diagnoses_refined = diagnoses_long_df_refined[diagnoses_long_df_refined['ICD10_code'].isin(codes_to_keep_refined)]

# Apply one-hot encoding on the filtered ICD10 codes, grouping by the original index to align with the original dataframe
one_hot_encoding_refined = pd.get_dummies(filtered_diagnoses_refined['ICD10_code'],dummy_na=False).groupby(level=0).max()

# Merge with the original dataframe excluding the 'Diagnoses - ICD10' column
optimized_df_without_extra_index = df.drop(columns=['Diagnoses - ICD10']).join(one_hot_encoding_refined)

optimized_df_without_extra_index.drop(columns=[""],errors="ignore",inplace=True)
# Verify the transformation by displaying the first few rows
optimized_df_without_extra_index

## the empty "" col is cases with 0 diagnoses = all nans . it is ok !

9707 # all code_counts
133 # codes_to_keep_refined
CPU times: user 5.42 s, sys: 538 ms, total: 5.96 s
Wall time: 5.97 s

,Participant ID,Year of birth,Sex,A09.9 Gastroenteritis and colitis of unspecified origin,"A41.9 Septicaemia, unspecified",C44.3 Skin of other and unspecified parts of face,"C50.9 Breast, unspecified",C61 Malignant neoplasm of prostate,D12.5 Sigmoid colon,"D25.9 Leiomyoma of uterus, unspecified",...,Z90.4 Acquired absence of other parts of digestive tract,Z90.7 Acquired absence of genital organ(s),"Z91.0 Personal history of allergy, other than to drugs and biological substances",Z92.1 Personal history of long-term (current) use of anticoagulants,Z92.2 Personal history of long-term (current) use of other medicaments,Z92.3 Personal history of irradiation,Z92.6 Personal history of chemotherapy for neoplastic disease,Z95.5 Presence of coronary angioplasty implant and graft,Z96.1 Presence of intraocular lens,Z96.6 Presence of orthopaedic joint implants
1,1000053,1944.0,Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1000163,1953.0,Male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1000561,1962.0,Female,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,1000981,1956.0,Female,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,1001399,1957.0,Male,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502391,6025353,1954.0,Male,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
502394,6025431,1962.0,Male,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
502400,6025660,1962.0,Female,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
502403,6025855,1954.0,Female,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
502409,6026188,1960.0,Male,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

* there's still rows with all nans? why that vs 0?

In [17]:
# optimized_df_without_extra_index[optimized_df_without_extra_index[""]>0]
# df.loc[df["Participant ID"]==1004017]

In [18]:
optimized_df_without_extra_index.columns

Index(['Participant ID', 'Year of birth', 'Sex',
       'A09.9 Gastroenteritis and colitis of unspecified origin',
       'A41.9 Septicaemia, unspecified',
       'C44.3 Skin of other and unspecified parts of face',
       'C50.9 Breast, unspecified', 'C61 Malignant neoplasm of prostate',
       'D12.5 Sigmoid colon', 'D25.9 Leiomyoma of uterus, unspecified',
       ...
       'Z90.4 Acquired absence of other parts of digestive tract',
       'Z90.7 Acquired absence of genital organ(s)',
       'Z91.0 Personal history of allergy, other than to drugs and biological substances',
       'Z92.1 Personal history of long-term (current) use of anticoagulants',
       'Z92.2 Personal history of long-term (current) use of other medicaments',
       'Z92.3 Personal history of irradiation',
       'Z92.6 Personal history of chemotherapy for neoplastic disease',
       'Z95.5 Presence of coronary angioplasty implant and graft',
       'Z96.1 Presence of intraocular lens',
       'Z96.6 Presence of orthopaedic joint implants'],
      dtype='object', length=135)

In [26]:
optimized_df_without_extra_index.Sex = optimized_df_without_extra_index.Sex =="Male"

optimized_df_without_extra_index = optimized_df_without_extra_index.rename(columns={'Participant ID':"id"}).set_index("id")

In [28]:
optimized_df_without_extra_index.to_parquet("df_diag_codes_flat2k.parquet")

In [27]:
optimized_df_without_extra_index

,Year of birth,Sex,A09.9 Gastroenteritis and colitis of unspecified origin,"A41.9 Septicaemia, unspecified",C44.3 Skin of other and unspecified parts of face,"C50.9 Breast, unspecified",C61 Malignant neoplasm of prostate,D12.5 Sigmoid colon,"D25.9 Leiomyoma of uterus, unspecified","D50.9 Iron deficiency anaemia, unspecified",...,Z90.4 Acquired absence of other parts of digestive tract,Z90.7 Acquired absence of genital organ(s),"Z91.0 Personal history of allergy, other than to drugs and biological substances",Z92.1 Personal history of long-term (current) use of anticoagulants,Z92.2 Personal history of long-term (current) use of other medicaments,Z92.3 Personal history of irradiation,Z92.6 Personal history of chemotherapy for neoplastic disease,Z95.5 Presence of coronary angioplasty implant and graft,Z96.1 Presence of intraocular lens,Z96.6 Presence of orthopaedic joint implants
id,,,,,,,,,,,,,,,,,,,,,
1000053,1944.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000163,1953.0,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000561,1962.0,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1000981,1956.0,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1001399,1957.0,True,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6025353,1954.0,True,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
6025431,1962.0,True,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6025660,1962.0,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6025855,1954.0,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6026188,1960.0,True,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0